2025-07-18 20:25:46,758 - fastapi - ERROR - Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

2025-07-18 20:27:02,282 - __main__ - INFO - Начало обработки файла: 636. В ООО КХ г.Дятьково.docx
2025-07-18 20:27:02,285 - __main__ - INFO - Временный файл создан: C:\Users\CD92~1\AppData\Local\Temp\tmp2zc4zd_t.docx (размер: 25945 байт)
2025-07-18 20:27:02,285 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:27:02,321 - __main__ - INFO - Найдено 2 записей
2025-07-18 20:27:02,322 - __main__ - CRITICAL - Критическая ошибка: name 'grouped' is not defined
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 146, in generate_protocols
    logger.info(f"Данные сгруппированы по программам: {list(grouped.keys())}")
                                                            ^^^^^^^
NameError: name 'grouped' is not defined

2025-07-18 20:27:02,324 - __main__ - INFO - Временный файл удален: C:\Users\CD92~1\AppData\Local\Temp\tmp2zc4zd_t.docx
2025-07-18 20:27:37,186 - __main__ - INFO - Начало обработки файла: 636. В ООО КХ г.Дятьково.docx
2025-07-18 20:27:37,189 - __main__ - INFO - Временный файл создан: C:\Users\CD92~1\AppData\Local\Temp\tmpzg9slgv1.docx (размер: 25945 байт)
2025-07-18 20:27:37,190 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:27:37,225 - __main__ - INFO - Найдено 2 записей
2025-07-18 20:27:37,226 - __main__ - INFO - Данные сгруппированы по программам: ['']
2025-07-18 20:27:37,226 - __main__ - INFO - Номер заявки: Номер, Организация: Организация
2025-07-18 20:27:37,227 - __main__ - INFO - Выходная директория: C:\Users\CD92~1\AppData\Local\Temp\tmpd7v5ka3i
2025-07-18 20:27:37,227 - __main__ - INFO - Обработка программы  (2 человек)
2025-07-18 20:27:37,243 - __main__ - ERROR - Ошибка при обработке программы : invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 158, in generate_protocols
    if int(program) > 5:
       ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

2025-07-18 20:27:37,244 - __main__ - ERROR - Не удалось сгенерировать ни одного файла
2025-07-18 20:27:37,244 - __main__ - CRITICAL - Критическая ошибка: 400: Не удалось сгенерировать файлы
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 204, in generate_protocols
    raise HTTPException(status_code=400, detail="Не удалось сгенерировать файлы")
fastapi.exceptions.HTTPException: 400: Не удалось сгенерировать файлы

2025-07-18 20:27:37,246 - __main__ - INFO - Временный файл удален: C:\Users\CD92~1\AppData\Local\Temp\tmpzg9slgv1.docx
2025-07-18 20:29:11,831 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.doc
2025-07-18 20:29:11,834 - __main__ - INFO - Временный файл создан: C:\Users\CD92~1\AppData\Local\Temp\tmp94emdzy4.docx (размер: 50688 байт)
2025-07-18 20:29:11,834 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:29:11,882 - __main__ - CRITICAL - Критическая ошибка: file 'C:\Users\CD92~1\AppData\Local\Temp\tmp94emdzy4.docx' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 143, in generate_protocols
    rows = parse_applications(tmp_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 69, in parse_applications
    doc = Document(path)
          ^^^^^^^^^^^^^^
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\venv\Lib\site-packages\docx\api.py", line 30, in Document
    raise ValueError(tmpl % (docx, document_part.content_type))
ValueError: file 'C:\Users\CD92~1\AppData\Local\Temp\tmp94emdzy4.docx' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'

2025-07-18 20:29:11,883 - __main__ - INFO - Временный файл удален: C:\Users\CD92~1\AppData\Local\Temp\tmp94emdzy4.docx
2025-07-18 20:31:42,156 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.doc
2025-07-18 20:31:42,158 - __main__ - INFO - Временный файл создан: 636. ООО КХ г. Дятьково.doc (размер: 50688 байт)
2025-07-18 20:31:42,159 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:31:42,163 - __main__ - CRITICAL - Критическая ошибка: file '636. ООО КХ г. Дятьково.doc' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 143, in generate_protocols
    rows = parse_applications(tmp_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 69, in parse_applications
    doc = Document(path)
          ^^^^^^^^^^^^^^
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\venv\Lib\site-packages\docx\api.py", line 30, in Document
    raise ValueError(tmpl % (docx, document_part.content_type))
ValueError: file '636. ООО КХ г. Дятьково.doc' is not a Word file, content type is 'application/vnd.openxmlformats-officedocument.themeManager+xml'

2025-07-18 20:31:42,178 - __main__ - ERROR - Ошибка при удалении временного файла: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: '636. ООО КХ г. Дятьково.doc'
2025-07-18 20:33:07,252 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.docx
2025-07-18 20:33:07,253 - __main__ - INFO - Временный файл создан: 636. ООО КХ г. Дятьково.docx (размер: 21739 байт)
2025-07-18 20:33:07,255 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:33:07,265 - __main__ - INFO - Найдено 4 записей
2025-07-18 20:33:07,265 - __main__ - INFO - Данные сгруппированы по программам: ['1', '2', '3', '4', '8', '22', '9', '29', '16', '17', '18', '19', '23', '24']
2025-07-18 20:33:07,265 - __main__ - INFO - Номер заявки: 636, Организация: ООО КХ г. Дятьково
2025-07-18 20:33:07,266 - __main__ - INFO - Выходная директория: C:\Users\CD92~1\AppData\Local\Temp\tmp187ifb5u
2025-07-18 20:33:07,266 - __main__ - INFO - Обработка программы 1 (2 человек)
2025-07-18 20:33:07,434 - __main__ - INFO - Обработка программы 2 (2 человек)
2025-07-18 20:33:07,472 - __main__ - INFO - Обработка программы 3 (2 человек)
2025-07-18 20:33:07,502 - __main__ - INFO - Обработка программы 4 (2 человек)
2025-07-18 20:33:07,534 - __main__ - INFO - Обработка программы 8 (1 человек)
2025-07-18 20:33:07,585 - __main__ - INFO - Обработка программы 22 (1 человек)
2025-07-18 20:33:07,632 - __main__ - INFO - Обработка программы 9 (1 человек)
2025-07-18 20:33:07,677 - __main__ - INFO - Обработка программы 29 (1 человек)
2025-07-18 20:33:07,719 - __main__ - INFO - Обработка программы 16 (1 человек)
2025-07-18 20:33:07,770 - __main__ - INFO - Обработка программы 17 (1 человек)
2025-07-18 20:33:07,813 - __main__ - INFO - Обработка программы 18 (1 человек)
2025-07-18 20:33:07,855 - __main__ - INFO - Обработка программы 19 (1 человек)
2025-07-18 20:33:07,910 - __main__ - INFO - Обработка программы 23 (1 человек)
2025-07-18 20:33:07,963 - __main__ - INFO - Обработка программы 24 (1 человек)
2025-07-18 20:33:08,007 - __main__ - ERROR - Не удалось сгенерировать ни одного файла
2025-07-18 20:33:08,007 - __main__ - CRITICAL - Критическая ошибка: 400: Не удалось сгенерировать файлы
Traceback (most recent call last):
  File "C:\Users\Рамиль\PycharmProjects\Заявка_протокол_посещаемость\app.py", line 204, in generate_protocols
    raise HTTPException(status_code=400, detail="Не удалось сгенерировать файлы")
fastapi.exceptions.HTTPException: 400: Не удалось сгенерировать файлы

2025-07-18 20:33:08,008 - __main__ - ERROR - Ошибка при удалении временного файла: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: '636. ООО КХ г. Дятьково.docx'
2025-07-18 20:34:43,456 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.docx
2025-07-18 20:34:43,458 - __main__ - INFO - Временный файл создан: 636. ООО КХ г. Дятьково.docx (размер: 21739 байт)
2025-07-18 20:34:43,458 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:34:43,471 - __main__ - INFO - Найдено 4 записей
2025-07-18 20:34:43,472 - __main__ - INFO - Данные сгруппированы по программам: ['1', '2', '3', '4', '8', '22', '9', '29', '16', '17', '18', '19', '23', '24']
2025-07-18 20:34:43,472 - __main__ - INFO - Номер заявки: 636, Организация: ООО КХ г. Дятьково
2025-07-18 20:34:43,472 - __main__ - INFO - Выходная директория: C:\Users\CD92~1\AppData\Local\Temp\tmpy3p4duql
2025-07-18 20:34:43,473 - __main__ - INFO - Обработка программы 1 (2 человек)
2025-07-18 20:34:43,533 - __main__ - INFO - Обработка программы 2 (2 человек)
2025-07-18 20:34:43,569 - __main__ - INFO - Обработка программы 3 (2 человек)
2025-07-18 20:34:43,597 - __main__ - INFO - Обработка программы 4 (2 человек)
2025-07-18 20:34:43,632 - __main__ - INFO - Обработка программы 8 (1 человек)
2025-07-18 20:34:43,697 - __main__ - INFO - Обработка программы 22 (1 человек)
2025-07-18 20:34:43,786 - __main__ - INFO - Обработка программы 9 (1 человек)
2025-07-18 20:34:43,853 - __main__ - INFO - Обработка программы 29 (1 человек)
2025-07-18 20:34:43,916 - __main__ - INFO - Обработка программы 16 (1 человек)
2025-07-18 20:34:43,972 - __main__ - INFO - Обработка программы 17 (1 человек)
2025-07-18 20:34:44,031 - __main__ - INFO - Обработка программы 18 (1 человек)
2025-07-18 20:34:44,084 - __main__ - INFO - Обработка программы 19 (1 человек)
2025-07-18 20:34:44,134 - __main__ - INFO - Обработка программы 23 (1 человек)
2025-07-18 20:34:44,205 - __main__ - INFO - Обработка программы 24 (1 человек)
2025-07-18 20:34:44,263 - __main__ - ERROR - Ошибка при удалении временного файла: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: '636. ООО КХ г. Дятьково.docx'
2025-07-18 20:37:17,172 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.docx
2025-07-18 20:37:17,175 - __main__ - INFO - Временный файл создан: 636. ООО КХ г. Дятьково.docx (размер: 21739 байт)
2025-07-18 20:37:17,175 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:37:17,187 - __main__ - INFO - Найдено 4 записей
2025-07-18 20:37:17,187 - __main__ - INFO - Данные сгруппированы по программам: ['1', '2', '3', '4', '8', '22', '9', '29', '16', '17', '18', '19', '23', '24']
2025-07-18 20:37:17,189 - __main__ - INFO - Номер заявки: 636, Организация: ООО КХ г. Дятьково
2025-07-18 20:37:17,189 - __main__ - INFO - Выходная директория: C:\Users\CD92~1\AppData\Local\Temp\tmpfuew9uut
2025-07-18 20:37:17,190 - __main__ - INFO - Обработка программы 1 (2 человек)
2025-07-18 20:37:17,244 - __main__ - INFO - Обработка программы 2 (2 человек)
2025-07-18 20:37:17,276 - __main__ - INFO - Обработка программы 3 (2 человек)
2025-07-18 20:37:17,307 - __main__ - INFO - Обработка программы 4 (2 человек)
2025-07-18 20:37:17,341 - __main__ - INFO - Обработка программы 8 (1 человек)
2025-07-18 20:37:17,400 - __main__ - INFO - Обработка программы 22 (1 человек)
2025-07-18 20:37:17,464 - __main__ - INFO - Обработка программы 9 (1 человек)
2025-07-18 20:37:17,538 - __main__ - INFO - Обработка программы 29 (1 человек)
2025-07-18 20:37:17,625 - __main__ - INFO - Обработка программы 16 (1 человек)
2025-07-18 20:37:17,686 - __main__ - INFO - Обработка программы 17 (1 человек)
2025-07-18 20:37:17,733 - __main__ - INFO - Обработка программы 18 (1 человек)
2025-07-18 20:37:17,774 - __main__ - INFO - Обработка программы 19 (1 человек)
2025-07-18 20:37:17,816 - __main__ - INFO - Обработка программы 23 (1 человек)
2025-07-18 20:37:17,875 - __main__ - INFO - Обработка программы 24 (1 человек)
2025-07-18 20:37:18,111 - __main__ - ERROR - Ошибка при удалении временного файла: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: '636. ООО КХ г. Дятьково.docx'
2025-07-18 20:46:35,493 - __main__ - INFO - Начало обработки файла: 636. ООО КХ г. Дятьково.docx
2025-07-18 20:46:35,496 - __main__ - INFO - Временный файл создан: 636. ООО КХ г. Дятьково.docx (размер: 21739 байт)
2025-07-18 20:46:35,496 - __main__ - INFO - Парсинг данных из файла...
2025-07-18 20:46:35,512 - __main__ - INFO - Найдено 4 записей
2025-07-18 20:46:35,513 - __main__ - INFO - Данные сгруппированы по программам: ['1', '2', '3', '4', '8', '22', '9', '29', '16', '17', '18', '19', '23', '24']
2025-07-18 20:46:35,514 - __main__ - INFO - Номер заявки: 636, Организация: ООО КХ г. Дятьково
2025-07-18 20:46:35,514 - __main__ - INFO - Выходная директория: C:\Users\CD92~1\AppData\Local\Temp\tmp5dg2gg9g
2025-07-18 20:46:35,515 - __main__ - INFO - Обработка программы 1 (2 человек)
2025-07-18 20:46:35,578 - __main__ - INFO - Обработка программы 2 (2 человек)
2025-07-18 20:46:35,614 - __main__ - INFO - Обработка программы 3 (2 человек)
2025-07-18 20:46:35,654 - __main__ - INFO - Обработка программы 4 (2 человек)
2025-07-18 20:46:35,699 - __main__ - INFO - Обработка программы 8 (1 человек)
2025-07-18 20:46:35,773 - __main__ - INFO - Обработка программы 22 (1 человек)
2025-07-18 20:46:35,843 - __main__ - INFO - Обработка программы 9 (1 человек)
2025-07-18 20:46:35,912 - __main__ - INFO - Обработка программы 29 (1 человек)
2025-07-18 20:46:35,995 - __main__ - INFO - Обработка программы 16 (1 человек)
2025-07-18 20:46:36,056 - __main__ - INFO - Обработка программы 17 (1 человек)
2025-07-18 20:46:36,117 - __main__ - INFO - Обработка программы 18 (1 человек)
2025-07-18 20:46:36,200 - __main__ - INFO - Обработка программы 19 (1 человек)
2025-07-18 20:46:36,268 - __main__ - INFO - Обработка программы 23 (1 человек)
2025-07-18 20:46:36,330 - __main__ - INFO - Обработка программы 24 (1 человек)
2025-07-18 20:46:36,706 - __main__ - ERROR - Ошибка при удалении временного файла: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: '636. ООО КХ г. Дятьково.docx'
